Test coverage using github workflow
With the current travis configuration, installation of covr failed,
presumably because of the use of the Xenial distribution which is
rather outdated meanwhile. The error occurred when installation of
curl was attempted on travis:

Error: C++17 standard requested but CXX17 is not defined